# Dependencies
markdown:         redcarpet
redcarpet: 
    extensions: ["fenced_code_blocks", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Pai
tagline:          'To be a programmer.'
description:      'Life is a competition with yourself.'
url:              http://dragon8897.github.io
baseurl:          /

author:
  name:           'Pai'
  url:            http://dragon8897.github.io/

paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde

gems:		   [jekyll-paginate]
